AWSTemplateFormatVersion: '2010-09-09'
Description: "Create Perforce Servers"

Parameters: 
  InstanceType: 
    Type: String
    Default: c5.4xlarge
    AllowedValues:
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
    Description: "Select Perforce server EC2 instance type. Default is c5.4xlarge."
  KeyPairName:
    Description: "Public/private key pairs allow you to securely connect to your instance after it launches"
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Type: "String"
    Default: "ami-08a702a5b23838980"
    Description: "Perforce-Helix-Core-AMI-Base-2020.1"
  PerforceAZ:
    Type: "String"
  ServerName:
    Type: "String"
  ServerDescription:
    Type: "String"
  ServerID:
    Type: "String"
  SubnetId:
    Type: "String"
  PrivateIpAddress:
    Type: "String"
  PerforceSecurityGroup:
    Type: "String"
  gw1:
    Type: "String"
  DepotVolumeType:
    Type: String
    Default: st1
    AllowedValues: 
      - st1
      - gp2
    Description: "Select either ST1 or GP2."
  DepotVolumeSize:
    Type: String
    Default: '1024'
    Description: "The size of the EBS volume attached for Depot."
  LogVolumeSize:
    Type: String
    Default: '128'
    Description: "The size of the EBS volume attached for Log."
  MetadataVolumeType:
    Type: String
    Default: gp2
    AllowedValues: 
      - gp2
      - io1
    Description: "Select either GP2 or IO1."
  MetadataVolumeSize:
    Type: String
    Default: '64'
    Description: "The size of the EBS volume attached for Metadata."
  MetadataProvisionedIops:
    Type: "String"
    ConstraintDescription: "Range is 100 to 64000 for Provisioned IOPS SSD volumes."
    Description: "Set the provisioned IOPs between 100 and 64000. Only set if you are choosing io1 for your metadata volume type."
  EC2Profile:
    Type: "String"
    Description: "EC2 profile setting for IAM role"

Resources:
  PerforceEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  # Setup EBS volumes
  VolumeHxlogs:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref PerforceAZ
      Size:
        Ref: LogVolumeSize
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: !Sub ${ServerName}-hxlogs
      - Key: ServerID
        Value: !Ref ServerID
  VolumeHxdepots:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref PerforceAZ
      Encrypted: true
      Size:
        Ref: DepotVolumeSize
      VolumeType: gp2
      Tags:
      - Key: ServerID
        Value: !Ref ServerID
      - Key: Name
        Value: !Sub ${ServerName}-hxdepots
  VolumeHxmetadata:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Ref PerforceAZ
      Size:
        Ref: MetadataVolumeSize
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: !Sub ${ServerName}-hxmetadata
      - Key: ServerID
        Value: !Ref ServerID
  # setup EC2 instance & perforce
  PerforceServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref PerforceAZ
      DisableApiTermination: 'false'
      InstanceInitiatedShutdownBehavior: stop
      EbsOptimized: 'true'
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      Monitoring: 'true'
      IamInstanceProfile: !Ref EC2Profile
      Tags:
      - Key: Name
        Value: !Ref ServerName
      - Key: Description
        Value: !Ref ServerDescription
      - Key: ServerID
        Value: !Ref ServerID
      Volumes:
      - Device: /dev/sdb
        VolumeId: !Ref VolumeHxdepots
      - Device: /dev/sdc
        VolumeId: !Ref VolumeHxlogs
      - Device: /dev/sdd
        VolumeId: !Ref VolumeHxmetadata
      NetworkInterfaces:
      - DeleteOnTermination: 'true'
        Description: Primary network interface
        DeviceIndex: 0
        SubnetId: !Ref SubnetId
        PrivateIpAddresses:
        - PrivateIpAddress: !Ref PrivateIpAddress
          Primary: 'true'
        GroupSet:
        - !Ref PerforceSecurityGroup
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          hostname ${ServerID}
          
          # Install packages 
          yum -y update

          yum -y install aws-cfn-bootstrap
          # Install the files and packages from the metadata
          # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/cfn-init.html
          /opt/aws/bin/cfn-init -v --configsets default --stack ${AWS::StackName} --resource PerforceServerInstance --region ${AWS::Region}
          # Signal the status from cfn-init
          # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/cfn-signal.html
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource PerforceServerInstance --region ${AWS::Region} 

    Metadata:
      # https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
      AWS::CloudFormation::Init:
        configSets: 
          default: 
            - "01_config_setup_volumes"
        01_config_setup_volumes:
          commands:
            # Mount hxdepots
            01_setup_hxdepots:
              command: "mkfs -t xfs /dev/sdb && mkdir /hxdepots && mount /dev/sdb /hxdepots"
              ignoreErrors: false
            # Mount hxlogs
            02_setup_hxlogs:
              command: "mkfs -t xfs /dev/sdc && mkdir /hxlogs && mount /dev/sdc /hxlogs"
              ignoreErrors: false
            # Mount hxmetadata
            03_setup_hxmetadata:
              command: "mkfs -t xfs /dev/sdd && mkdir /hxmetadata && mount /dev/sdd /hxmetadata"
              ignoreErrors: false
            # Configure /etc/fstab
            04_add_config_to_fstab:
              command: blkid /dev/sdb | awk -v OFS="   " '{print $2,"/hxdepots","xfs","defaults,nofail","0","2"}' >> /etc/fstab
              ignoreErrors: false
            05_add_config_to_fstab:
              command: blkid /dev/sdc | awk -v OFS="   " '{print $2,"/hxlogs","xfs","defaults,nofail","0","2"}' >> /etc/fstab
              ignoreErrors: false
            06_add_config_to_fstab:
              command: blkid /dev/sdd | awk -v OFS="   " '{print $2,"/hxmetadata","xfs","defaults,nofail","0","2"}' >> /etc/fstab
              ignoreErrors: false
        
  assocEIP:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId:
        Fn::GetAtt:
        - PerforceEIP
        - AllocationId
      InstanceId: !Ref PerforceServerInstance
              
Outputs:
  EC2InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref PerforceServerInstance
  PerforceEIP:
    Description: Elastic IP Adress attached to Perforce server
    Value: !Ref PerforceEIP
